### ISSUE TITLE
Release for distro packaging

### ISSUE THREAD

**Issue by maxice8** [braincorp/partfs#3]
We are trying to package this on Void Linux but we need a tagged release to get a tarball from.

https://github.com/void-linux/void-packages/pull/9274

**Comment by codymgriffin** [comment]
@maxice8 - so sorry for the delay.  I will put a quick tag on develop ASAP.

**Comment by codymgriffin** [comment]
@maxice8 I've created a 0.1.0 tag for you.  Cheers!

**Comment by maxice8** [comment]
https://github.com/void-linux/void-packages/commit/7ed64abba1d06f82393b00f221e468f20af40334 it is now in.
